### PR TITLE
Update video_mode.py

### PR DESCRIPTION
**Pull request by magicse**
Added support for video files in MTS format

### CODE REVIEW

**Comment by semjon00** [comment]
Hello, thank you for contributing!
Did you test that it works at least with your video?
There is "suffix.lower" in the commit that should be "suffix.lower()" (happens two times).

If this is addressed and code otherwise works I am happy to merge this :)

**Comment by magicse** [comment]
Yes it wotk. I'm currently calculating the depthmap for my videos. thank You.

**Comment by magicse** [comment]
> suffix.lower()

It need for all - if suffix.lower() because it case sensitivity? but sometime  suffix could be like mts or MTS or MP4 or mp4 ))

**Comment by semjon00** [comment]
Merged :)

There are more things that can be improved in video generation. I would be glad if you submit more code with improvements.

**Pull request merged**
