### PR TITLE
improvements for stereo image generation

### PR DESCRIPTION
**Pull request by semjon00**
Hello!

Thanks to all the contributors of this fantastic technology and the script.

This code adds two new options for stereo image generation:
1) Alternative algorithm for filling in empty space. For each pixel in a line of empty pixels, it colors them depending not only on the colors of pixels to the left and/or right, but also depending on distance to them. This may make the edges less visible/noticeable. The implementation is CPU heavy (slow), would be great if somebody could do the same, but faster.
2) An option to change how the deviation is distributed between eyes. Currently, the right image is copied directly from the source and the left image is changed. This means that all the (inevitable) distortion from filling up gaps will end up in the left image. For me, this is inconvenient, since my main (leading) eye is the left eye - this means the perceived distortion is much more visible to me than to people, whose main eye is right. This option allows to move the distortion to the right image, or split it in-between two images (to my eye, it makes distortion it less noticeable overall).

Hope I did not break anything in the process.

Now some demos :)
Settings: deviation is 12 (24 would be too extreme), res101 model, 384x384 net, BOOST enabled. The picture is taken from the discussion #45.
_Current_
original
_With option 1 enabled_
option1
_Option 1 enabled and the deviation is perfectly balanced_
options12

Waiting for improvement suggestions :)

Cheers

### CODE REVIEW

**Comment by semjon00** [comment]
Wow, numba speed bonus is indeed insane! Thanks, now I know this thing exists.

I've got carried away when improving the code, probably more than I would like to. Wish I had noticed (and changed) some of these things before creating the initial MR.. Anyways, new changes are:
- apply_stereo_deviation now uses numba
- correctness fix (I think...) for hard_horizontal, now should actually split the gap in two
- a minor change that I forgot to make in the first part of the function (reversing the sweep direction)
- optimizations for both gap filling techniques
- fix for a potential situation where completely black pixels are regarded as gap
- default gap filling technique is changed to soft_horizontal, IMHO it is fast-enough now

**Comment by semjon00** [comment]
Thank you for merging, that was really fast :)
The last change was made 15 minutes ago, was that version the one you in intended to merge?

**Comment by thygate** [comment]
Excellent! I see you added the numba jit too. I was looking into cython first, but that would require an installed c compiler and would complicate being multi platform. So some more googling revealed numba which uses llvm. I was expecting a good speed increase as all the interpreted languages struggle with this, but the increase in speed really is insane.

I'll do a full test to check if nothing broke, and update the version and readme

I was aware of that bug with full lines of black, great if that's solved too.

Wait, did I mess up the merge ?

**Comment by semjon00** [comment]
I left some debug code inside

**Comment by semjon00** [comment]
Thank you for reviewing and accepting my changes!

**Comment by thygate** [comment]
I'll remove the _core wrap too, also updated the ui in Script.ui to include the dropdown.

You're very welcome, and thank you for the improvements, I've not fully tested it yet but the results look good, and the original method is still supported, so great.

Still testing ..

**Comment by tufeixp** [comment]
I can see the uneven left and right image problem fixed here, but code removed at commit 58245f7. Why? @semjon00

**Comment by semjon00** [comment]
@tufeixp I don't really understand what do you mean. What do you mean by "uneven"? Do you suggest that this commit (https://github.com/thygate/stable-diffusion-webui-depthmap-script/commit/58245f76c229114c6f326ff7f2d60e842941ef4c) broke it? This commit (as far as I remember) should not have changed any logic, only simplify the code. The removed code was a duplicate from stereo_generation.py What fill technique do you use?

**Comment by tufeixp** [comment]
uneven means  unbalanced deviation, no matter what hole fill method I choose, the result is unbalanced.

**Comment by semjon00** [comment]
@tufeixp Please try putting the stereo balance slider in the middle, try different stereo balance values

**Comment by tufeixp** [comment]
image
set balance to -0.5, the right should on the right eye image has no gap.

@semjon00 Sure I have played with the balance slider settings as well. The default 0 should be defined as balanced where the gap fix should perceived on both side, however it's only on the left part of the dual images. Drag it to other values  won't change it.

**Comment by semjon00** [comment]
@MavenDE Just remembered you notified me of the same/similar problem. Please update the extension and see if it fixed the issue.

**Pull request merged**
