### PR TITLE
Large refactor

### PR DESCRIPTION
**Pull request by semjon00**
Status (2023-07-18): needs merging

~~This is expected to be semi-broken. My plan currently is to refactor it more, and only then do a good test to see what is broken (and fix it). Still would appreciate nods into the right directions - what broke and needs fixing, what could be improved in the refactor, what else is worth to refactor.~~

The changed line count is inflated by changing tabs to spaces. Some editors (e.g. Pycharm 2023.1) will show whitespace edits differently than style and significant edits. Also, I moved code to different files.

### CODE REVIEW

**Comment by semjon00** [comment]
@graemeniedermayer @thygate I would kindly ask you to keep an eye on this, as this will create totally massive merge conflicts if main branch receives significant changes while this is in the works.

**Comment by semjon00** [comment]
@thygate 
I am not refactoring invert_depth. Did I get all this right?

| invert_depth is enabled with this option | Desired effect of invert_depth on the option |
| ------------- |-------------|
| Clip and renormalize      | Resulting image is inverted and clipped |
| Generate stereoscopic image(s) | Resulting depthmap is inverted, no effect on the stereo image | 
| Generate simple 3D mesh | No effect, mesh is exactly as if invert_depth was disabled |
| Generate 3D inpainted mesh | No effect, mesh is exactly as if invert_depth was disabled |
| Remove background | Does not depend on the generated depthmap, no effect |

**Comment by semjon00** [comment]
@thygate 
Clipdepth (Clip and renormalize) is also quite tricky. Do you think these values are ok? Would you change something?

| clipdepth is enabled with this option | Desired effect of clipdepth on the option |
| ------------- |-------------|
| Invert depth      | Resulting image is inverted and clipped |
| Generate stereoscopic image(s) | Depending on whether it is clipped from below or above: the closest objects will appear as if distance to them is the same and/or the furthest objects will appear as having the same distance | 
| Generate simple 3D mesh | Mesh will be distorted along the depth axis |
| Generate 3D inpainted mesh | Mesh will be distorted along the depth axis |
| Remove background | Does not depend on the generated depthmap, no effect |

**Comment by semjon00** [comment]
@thygate 
(C)
There is an option to show depthmap, and to save depthmap. Do you think it would make sense to always show everything (depthmaps, stereoimages, etc.), but have an option called "save results" (or something like that), that would be enabled by default? This approach is marginally easier to implement and IMO would be more user-friendly.

**Comment by thygate** [comment]
(C) Yes! The show depthmap is a leftover from the very first version, it serves no purpose. Always showing everything that was generated would be the most intuitive I agree.

**Comment by thygate** [comment]
(B) The clip depth (far/near) function was something I implemented quickly and never really properly tested tbh ..
It was requested at some point, but I'm not sure anyone is actually using it, I believe it was for raw depthmap outputs only, I don't think, or can't think of a scenario where it would be useful for the other options, like generating stereo pairs or meshes ..
So the suggested outcomes seem fine.

**Comment by thygate** [comment]
(A) No effect for all seems like the correct approach to me, this option was meant for raw depthmap output only, since some external software requires it. It should have no effect on any of the options except clip and renormalize. So all seem good to me.

**Comment by semjon00** [comment]
@thygate Thank you! 
(A) Implemented :)
(B) (C) Workinhg on it...

**Comment by semjon00** [comment]
(D) net_w and net_h are assigned, but never used; net_width and net_height are actually used. I guess it should work differently... Do I get it right that every model has its original (suggested) net size, but sometimes it is beneficial to override it? How do you think: maybe the net size should be a dropdown with values: "default" (match model), "match image" and "custom", where custom shows two sliders for the net size? Or simply "match model size" and "match input size"?

**Comment by thygate** [comment]
(D) Yes correct, net_w and net_h were the initial model sizes, at the start the sliders would mirror this initial model size, but this changed at one point and I never removed them. Drop down would be fine, but not all models support all sizes, and tweaking the size manually can be beneficial to tune for detail. I would prefer to keep the option to manually set size.

**Comment by thygate** [comment]
For starters, thanks for all this work !! I'm doing some quick tests to see if anything is broken ..

**Comment by thygate** [comment]
zoedepth models run fast the first time i run them, and then very slow on each subsequent run :\

running on the same picture, the first time takes 2 seconds, each subsequent run with same params and image takes 40 secs ..

**Comment by thygate** [comment]
stereo image generation and both mesh generations seem to be fine.

**Comment by semjon00** [comment]
@thygate Oops, a logic error. Now should be fixed.

**Comment by semjon00** [comment]
@graemeniedermayer Oh! This sounds like a good idea. https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/282

**Comment by thygate** [comment]
When using "match net size" and leres I get this error 

```
DepthMap v0.4.0 (cc55be2f)
device: cuda
Loading model(s) ..
Computing output(s) ..
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: (False, 'u2net', False, False, 0, 1, False, 1, 'GPU', False, None, '', '', True, <PIL.Image.Image image mode=RGB size=1489x2514 at 0x1DCA543B9D0>, '0', False, False, False, None, False, False, False, True, True, False, 0, 512, 512, True, False, False, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 0, '∯background_removal∯background_removal_model∯boost∯clipdepth∯clipthreshold_far∯clipthreshold_near∯combine_output∯combine_output_axis∯compute_device∯custom_depthmap∯custom_depthmap_img∯depthmap_batch_input_dir∯depthmap_batch_output_dir∯depthmap_batch_reuse∯depthmap_input_image∯depthmap_mode∯gen_mesh∯gen_normal∯gen_stereo∯image_batch∯inpaint∯inpaint_vids∯invert_depth∯match_size∯mesh_occlude∯mesh_spherical∯model_type∯net_height∯net_width∯output_depth∯pre_depth_background_removal∯save_background_removal_masks∯save_outputs∯show_heat∯stereo_balance∯stereo_divergence∯stereo_fill∯stereo_modes∯stereo_separation') {}
    Traceback (most recent call last):
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\interface_webui.py", line 527, in run_generate
        outputs, mesh_fi, meshsimple_fi = core_generation_funnel(outpath, inputimages, inputdepthmaps, inputnames, inputs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\core.py", line 305, in core_generation_funnel
        raise e
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\core.py", line 170, in core_generation_funnel
        model_holder.get_raw_prediction(inputimages[count], net_width, net_height)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_generation.py", line 282, in get_raw_prediction
        raw_prediction = estimateleres(img, self.depth_model, net_width, net_height)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_generation.py", line 304, in estimateleres
        prediction = model.depth_model(img_torch)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\lib\multi_depth_model_woauxi.py", line 32, in forward
        out_logit = self.decoder_modules(lateral_out)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\lib\network_auxi.py", line 58, in forward
        x_4 = self.ffm1(features[1], x_8)  # 1/4
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\lib\network_auxi.py", line 209, in forward
        x = x + high_x
    RuntimeError: The size of tensor a (187) must match the size of tensor b (188) at non-singleton dimension 3

---
Traceback (most recent call last):
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>RuntimeError: The size of tensor a (187) must match the size of tensor b (188) at non-singleton dimension 3</div><div class='performance'><p class='time'>Time taken: <wbr>1.43s</p><p class='vram'>Torch active/reserved: 5274/6220 MiB, <wbr>Sys VRAM: 8192/8192 MiB (100.0%)</p></div>"]
```

when using leres and boost, seems to be for most models and boost : 
```

DepthMap v0.4.0 (cc55be2f)
device: cuda
Loading model(s) ..
Loading model weights from  ./models/leres/res101.pth
initialize network with normal
loading the model from ./models/pix2pix\latest_net_G.pth
*** Error completing request
*** Arguments: (False, 'u2net', True, False, 0, 1, False, 1, 'GPU', False, None, '', '', True, <PIL.Image.Image image mode=RGB size=1489x2514 at 0x1DCA9B9FFD0>, '0', False, False, False, None, False, False, False, False, True, False, 0, 448, 448, True, False, False, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 0, '∯background_removal∯background_removal_model∯boost∯clipdepth∯clipthreshold_far∯clipthreshold_near∯combine_output∯combine_output_axis∯compute_device∯custom_depthmap∯custom_depthmap_img∯depthmap_batch_input_dir∯depthmap_batch_output_dir∯depthmap_batch_reuse∯depthmap_input_image∯depthmap_mode∯gen_mesh∯gen_normal∯gen_stereo∯image_batch∯inpaint∯inpaint_vids∯invert_depth∯match_size∯mesh_occlude∯mesh_spherical∯model_type∯net_height∯net_width∯output_depth∯pre_depth_background_removal∯save_background_removal_masks∯save_outputs∯show_heat∯stereo_balance∯stereo_divergence∯stereo_fill∯stereo_modes∯stereo_separation') {}
    Traceback (most recent call last):
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\interface_webui.py", line 527, in run_generate
        outputs, mesh_fi, meshsimple_fi = core_generation_funnel(outpath, inputimages, inputdepthmaps, inputnames, inputs)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\core.py", line 137, in core_generation_funnel
        model_holder.ensure_models(model_type, device, boost)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_generation.py", line 60, in ensure_models
        self.reload()
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_generation.py", line 250, in reload
        self.move_models_to(self.device)
      File "C:\Users\thyga\Desktop\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap_generation.py", line 257, in move_models_to
        self.pix2pix_model.to(device)
    AttributeError: 'Pix2Pix4DepthModel' object has no attribute 'to'

---
Traceback (most recent call last):
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\thyga\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [gallery, textbox, model3d, html, html]
Received outputs:
    [None, "", "<div class='error'>AttributeError: &#x27;Pix2Pix4DepthModel&#x27; object has no attribute &#x27;to&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>4.07s</p><p class='vram'>Torch active/reserved: 6385/6404 MiB, <wbr>Sys VRAM: 8192/8192 MiB (100.0%)</p></div>"]
```

**Comment by semjon00** [comment]
Can reproduce the net size issue in the main branch, too. This happens if image has a weird size. Do you think the code should simply round the net dimensions to the nearest 32x?

**Comment by thygate** [comment]
Hehe, no worries, I'm very grateful for all the work you've put in this!

Ah and yes, I see it now,  (187) vs (188), my bad, I was a bit too fast with that report, sorry.

Rounding the dimensions upward to the next multiple of 32 is a great idea and will solve this problem too.

**Comment by semjon00** [comment]
😊

**Comment by graemeniedermayer** [comment]
I testing it out! It's looking good. The only bug I found was also on the main branch.

Zoe depth and pre_depth_background_removal don't seem to work together. This stems from RGB vs RGBA. It's a little tricky. I think the best solution would be to explicitly convert to RGB in the batched_background_removal function, but the alpha channel is used later to create the mask so I'll need to think about this a little bit.

**Comment by semjon00** [comment]
Found a problem with the script mode. I will fix it soon.

**Comment by semjon00** [comment]
Remove background tested.

**Comment by semjon00** [comment]
Both simple and inpainted meshes seem to generate fine. Videos, too.

**Comment by semjon00** [comment]
I've taken some time off (lots of stuff), but now I am back. I would like to get it merged - @thygate could you please do the last checks you have in mind and then Create a merge commit?

**Comment by semjon00** [comment]
Whoops, there has been an issue with this I did not find up until now: if model offloading is enabled, it will be offloaded only once, and then won't offload.

**Comment by semjon00** [comment]
And now we wait... Issues are bound to come, hopefully nothing that will be hiding for months like that one time I messed up a feature for 2+ months

**Comment by thygate** [comment]
I checked all features and everything seems to be working for me, if anything is to pop up, I assume it will be small stuff, or problems with packages .. I went over all your commits and read all your comments, thanks again for the thorough job of refactoring the hot mess that it was.

I did notice that just having some other extensions installed can change the torch hub checkpoint path, so the zoedepth models were redownloaded.

**Pull request merged**
