### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by semjon00**
This MR has 5 fixes to address various issues - the ones that were _relatively_ easy to fix.

@Lalimec Thank you for the "Improve including bundled code" fix! Please test if it works if you delete the repository and install it again.

@thygate ~~If you would like to allow me to close issues and push code, you may add me as a collaborator to this repository. I am usually busy, but I may occasionally throw in some fixes (well, hopefully they fix stuff and not break stuff 😅)~~ Thank you for making me a collaborator 😀

### CODE REVIEW

**Comment by Lalimec** [comment]
Happy that it worked! I will test it when I get the chance. Thanks for the pr finally lol.

**Comment by semjon00** [comment]
Please do not merge just yet, I think I have found a better way to "Improve including bundled code".

**Comment by semjon00** [comment]
The MR includes fixes to the stereo image generation that was actually **broken** before this. I am very sorry, it is my fault, I remember testing my changes - I honestly do not know how that even happened...

**Comment by ansj11** [comment]
why i can not find the changed file in thygate:main?

**Comment by semjon00** [comment]
@ansj11 
If you are seeing this MR, you are doing something weird 😅
Please follow the installation instructions.

**Pull request merged**
