### PR TITLE
v0.4.3

### PR DESCRIPTION
**Pull request by semjon00**
@thygate This is a significant update that still brings some refactoring with it. Please give these changes a look and tell me if anything needs polishing. I am particularly worried about the updates to the core. Would be nice to hear your and @graemeniedermayer 's opinion about the new feature :)

### CODE REVIEW

**Comment by graemeniedermayer** [comment]
Super exciting!

For video stabilisation. A very rudimentary way of doing it is alpha compositing the next frame over the current frame

`ffmpeg -fflags +genpts -i flickeringVideo.mp4 -fflags +genpts -i flickeringVideo.mp4 -filter_complex "[0:v]setpts=PTS-STARTPTS[top]; [1:v]setpts=PTS-STARTPTS+.033/TB, format=yuva420p, colorchannelmixer=aa=0.5[bottom]; [top][bottom]overlay=shortest=1" -c:v libx264 -crf 26 lessFlickeringVideo.mp4` (need to track down the source it was from somewhere on stackoverflow)

it helps remove the global flicker but it also suppresses the depth contrast.

Also I tried implementing https://github.com/ChenyangLEI/All-In-One-Deflicker in 16bit. It ran but the results were bad (for depthmaps).

**Comment by semjon00** [comment]
@graemeniedermayer Sorry, we have gotten a race condition here 😅 Please check out the latest commit, what do you think of this?

**Comment by semjon00** [comment]
@graemeniedermayer Another challenge is improving stereoimage generation. We are dropping out a ton of info that could be derived from the neighboring frames...

**Comment by graemeniedermayer** [comment]
Training high quality neural networks from scratch can be quite challenging. I think it would be ideal to find a known method that works for RGB and alter for 16 bit (Although they definitely are quite different). Although I strongly support any experimentation so if you have an for neural network training you should pursue it! My guess would be used you'd use a U-Net structure

> We are dropping out a ton of info that could be derived from the neighboring frames.

I feel like this is also going to cause the files to be much larger than they need to be too. 

There are also a number of NeRF projects that have started synthesising depth from videos. Some haven't released code yet, but many have promised to release code.

https://oasisyang.github.io/mononerf/
https://jonbarron.info/zipnerf/
https://localrf.github.io/ (I've been planning on testing this one out)

**Comment by semjon00** [comment]
> We are dropping out a ton of info that could be derived from the neighboring frames.

By this I meant that stereoscopic images still are being created frame-by-frame. Imagine a moving object - at every point in time it occludes some space. Since at different times different spaces are occluded, we may use information from different frames to reconstruct some of the occluded regions.

**Comment by semjon00** [comment]
I'll push, hopefully everything is ok 😅

**Pull request merged**
