### PR TITLE
Batch loop fix + small rembg updates

### PR DESCRIPTION
**Pull request by graemeniedermayer**
This is implementing @semjon00 's solution https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/302#issuecomment-1646565688 of passing a save function. 

**rembg update**

adding is-net. is-net is essentially a direct upgrade to u2-net. 

`pip install -U` rembg might be necessary to enable is-net. I would add an update to install.py but it's probably best to wait for things to stabilise with the large refactor. 

It's possible to integrate facebook's segment-anything model but it looks a little involved.

### CODE REVIEW

**Comment by semjon00** [comment]
Thanks for the effort on this! Do I get it right that adding isnet simply means allowing the two options to be passed to rembg?

I'd rather not merge as-is, there are some issues with how the loop workaround is implemented.
A) There are some commits that are not needed, which clutter git history. Also there is no guarantee that they don't undo some already implemented changes. This can be solved by rebasing the needed commit(s) to the target branch (thygate/stable-diffusion-webui-depthmap-script/main in this case) and deleting the unnecessary commits. For this, you first need to add a new remote. This is a way to tell git to look for branches and tags in more than one place at the same time.
B) This only works for from the tab, not from the script. Easy thing to miss... I too forget quite often which features do we have and which environments are used to launch everything (Python 3.8 🙃) 
C) Displaying options that are not actually available is not good.
D) Two completely separate changes in one commit - not that serious feature-wise, just makes some people feel like they are looking at this picture: [link](https://scontent-arn2-1.xx.fbcdn.net/v/t1.6435-9/102918185_3143073462422372_8456226980585319876_n.jpg?_nc_cat=103&cb=99be929b-59f725be&ccb=1-7&_nc_sid=730e14&_nc_ohc=IUMID7TaSL8AX_IUCIk&_nc_ht=scontent-arn2-1.xx&oh=00_AfBeEA7WyCN80aeY8_NAtUdgqaVeZ_M5UAd89ZyKmpMQjQ&oe=64E41FB5) 😅

However, I did not realize how little needs to be changed for the batch processing to output things right away! Thanks, this is a good approach while I think about `yield` - it potentially could be more clean than passing function could be. Also thanks for bringing attention to the rembg upgrade.

**Comment by graemeniedermayer** [comment]
Oh not sorry I should have squashed. 

C) Displaying options that are not actually available is not good. 

Anyone who installs new rembg will have these features usable. There's a bit of a history of rembg installations causing trouble https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/89 https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/115 . 

is-net is significnatly better than u2-net.

I mean they did seem pretty trivial line-wise but it seems I missed some things.

**Comment by semjon00** [comment]
Reinstalling rembg causes trouble... So you think it would be a bad idea to simply bump rembg to 2.0.50? That would be easy. It would make users very puzzled if they see options that do not work for them - so we could hide these two if rembg is too old for them. But that is also weird - we will need to explain that in order to get them, they must update rembg... which many of them don't know how to do.

AFAIK pip rembg package no longer enforces versions on the dependencies:
```
./python pipdeptree
...
rembg==2.0.49
├── numpy [required: Any, installed: 1.23.5]
├── onnxruntime [required: Any, installed: 1.15.1]
│   ├── coloredlogs [required: Any, installed: 15.0.1]
│   │   └── humanfriendly [required: >=9.1, installed: 10.0]
│   ├── flatbuffers [required: Any, installed: 23.5.26]
│   ├── numpy [required: >=1.24.2, installed: 1.23.5]
│   ├── packaging [required: Any, installed: 23.1]
│   ├── protobuf [required: Any, installed: 3.20.0]
│   └── sympy [required: Any, installed: 1.11.1]
│       └── mpmath [required: >=0.19, installed: 1.2.1]
├── opencv-python-headless [required: Any, installed: 4.8.0.74]
│   ├── numpy [required: >=1.19.3, installed: 1.23.5]
│   ├── numpy [required: >=1.17.3, installed: 1.23.5]
│   ├── numpy [required: >=1.23.5, installed: 1.23.5]
│   ├── numpy [required: >=1.21.2, installed: 1.23.5]
│   └── numpy [required: >=1.17.0, installed: 1.23.5]
├── Pillow [required: Any, installed: 9.5.0]
├── pooch [required: Any, installed: 1.7.0]
│   ├── packaging [required: >=20.0, installed: 23.1]
│   ├── platformdirs [required: >=2.5.0, installed: 3.8.0]
│   └── requests [required: >=2.19.0, installed: 2.28.1]
│       ├── certifi [required: >=2017.4.17, installed: 2022.12.7]
│       ├── charset-normalizer [required: >=2,<3, installed: 2.1.1]
│       ├── idna [required: >=2.5,<4, installed: 3.4]
│       └── urllib3 [required: >=1.21.1,<1.27, installed: 1.26.13]
├── PyMatting [required: Any, installed: 1.1.8]
│   ├── numba [required: !=0.49.0, installed: 0.57.1]
│   │   ├── llvmlite [required: >=0.40.0dev0,<0.41, installed: 0.40.1]
│   │   └── numpy [required: >=1.21,<1.25, installed: 1.23.5]
│   ├── numpy [required: >=1.16.0, installed: 1.23.5]
│   ├── Pillow [required: >=5.2.0, installed: 9.5.0]
│   └── scipy [required: >=1.1.0, installed: 1.11.1]
│       └── numpy [required: >=1.21.6,<1.28.0, installed: 1.23.5]
├── scikit-image [required: Any, installed: 0.20.0]
│   ├── imageio [required: >=2.4.1, installed: 2.31.1]
│   │   ├── numpy [required: Any, installed: 1.23.5]
│   │   └── Pillow [required: >=8.3.2, installed: 9.5.0]
│   ├── lazy-loader [required: >=0.1, installed: 0.3]
│   ├── networkx [required: >=2.8, installed: 3.0]
│   ├── numpy [required: >=1.21.1, installed: 1.23.5]
│   ├── packaging [required: >=20.0, installed: 23.1]
│   ├── Pillow [required: >=9.0.1, installed: 9.5.0]
│   ├── PyWavelets [required: >=1.1.1, installed: 1.4.1]
│   │   └── numpy [required: >=1.17.3, installed: 1.23.5]
│   ├── scipy [required: >=1.8, installed: 1.11.1]
│   │   └── numpy [required: >=1.21.6,<1.28.0, installed: 1.23.5]
│   └── tifffile [required: >=2019.7.26, installed: 2023.7.4]
│       └── numpy [required: Any, installed: 1.23.5]
├── scipy [required: Any, installed: 1.11.1]
│   └── numpy [required: >=1.21.6,<1.28.0, installed: 1.23.5]
└── tqdm [required: Any, installed: 4.65.0]
...
```

**Comment by graemeniedermayer** [comment]
> So you think it would be a bad idea to simply bump rembg to 2.0.50? That would be easy.

If they aren't enforcing dependencies it should be good! The last time I checked the repo had a lot more issues built up especially m1 compatibility, but those seem resolved.

I would also suggestion changing the default to "isnet-general-use". Also I vote changing the depth default to 'zoedepth_n (indoor)' without boost, but that's probably a more contentious default.

**Comment by semjon00** [comment]
Indeed, isnet-general-use usually looks a little bit nicer.
Changing to Zoedepth is interesting, too, but if I'd change, I would rather pick zoedepth_nk.
Also, I want to change default stereoimage generation mode to polylines_soft.

@thygate how do you feel about changing the defaults?

**Comment by semjon00** [comment]
@thygate Also, I want to bump rembg to 2.0.50. It seems safe to push, but I'd wait for you to ACK, maybe there is something I did not think about.

**Comment by semjon00** [comment]
For visibility:
My shortlog:
* Refactor rembg and push rembg update (improves extendability)
* Refactor parameter passing (improves API code and extendability)
* Fix (https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/302)

**Comment by thygate** [comment]
All fine for me. Reminds me, I need to change default mesh output format back to (binary) PLY as well.

Also @semjon00 I will get on the vispy backend issue asap, I will be back at my office tomorrow.

**Comment by semjon00** [comment]
Did not actually meant to push 0.4.2 just now 😮
But since there is nothing scary, I guess I'd rather just leave it there, don't want to rewrite history or revert everything.

**Comment by graemeniedermayer** [comment]
it looks like a typo snuck in https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/307 https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/308 

I think this is removing the last ".df" on line 56 of core.py

**Pull request closed without merging**
